const searchUrl = (query) =>
  `https://www.google.com/search?q=${encodeURIComponent(query)}`;

const mapsSearchUrl = (query) =>
  `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;

const hotel = {
  name: "The Broome Hotel",
  address: "431 Broome St, New York, NY 10013",
  lat: 40.7229,
  lng: -73.9976,
};

const tripDates = [
  { iso: "2026-04-15", label: "Wed 15" },
  { iso: "2026-04-16", label: "Thu 16" },
  { iso: "2026-04-17", label: "Fri 17" },
  { iso: "2026-04-18", label: "Sat 18" },
  { iso: "2026-04-19", label: "Sun 19" },
];

const neighborhoodCenters = {
  soho: { lat: 40.7233, lng: -74.0006 },
  nolita: { lat: 40.7234, lng: -73.9957 },
  noho: { lat: 40.7283, lng: -73.9936 },
  westVillage: { lat: 40.7332, lng: -74.0027 },
  greenwichVillage: { lat: 40.7312, lng: -73.9972 },
  eastVillage: { lat: 40.7282, lng: -73.9857 },
  lowerEastSide: { lat: 40.7182, lng: -73.9883 },
  chinatown: { lat: 40.7158, lng: -73.9970 },
  financialDistrict: { lat: 40.7077, lng: -74.0109 },
  meatpacking: { lat: 40.7391, lng: -74.0054 },
  williamsburg: { lat: 40.7178, lng: -73.9585 },
  greenpoint: { lat: 40.7248, lng: -73.9503 },
  fortGreene: { lat: 40.6886, lng: -73.9735 },
  brooklynHeights: { lat: 40.6960, lng: -73.9953 },
  cobbleHill: { lat: 40.6874, lng: -73.9970 },
  parkSlope: { lat: 40.6739, lng: -73.9785 },
  clintonHill: { lat: 40.6866, lng: -73.9668 },
};

const restaurants = [
  {
    id: "semma",
    name: "Semma",
    priority: "anchor",
    region: "manhattan",
    neighborhood: "West Village",
    neighborhoodKey: "westVillage",
    cuisine: "Indian",
    spend: "$$$",
    spendFor2: "$175-$240",
    summary: "The hardest-working downtown dinner flex that still feels fun instead of ceremonial.",
    tip: "Pre-order the Dungeness crab if this becomes your anchor reservation.",
    address: "60 Greenwich Ave, New York, NY 10011",
    bookingUrl: "https://www.semma.nyc/",
    websiteUrl: "https://www.semma.nyc/",
    sourceUrl: "https://www.semma.nyc/",
    sourceLabel: "Official site",
    booking: { kind: "rolling-days", daysBefore: 15, time: "09:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "lartusi",
    name: "L'Artusi",
    priority: "anchor",
    region: "manhattan",
    neighborhood: "West Village",
    neighborhoodKey: "westVillage",
    cuisine: "Italian",
    spend: "$$$",
    spendFor2: "$170-$230",
    summary: "Best all-around date-night safety pick if you want the room, the pasta, and the wine list.",
    tip: "Counter and bar seats are still a useful backup if the drop beats you.",
    address: "228 W 10th St, New York, NY 10014",
    bookingUrl: "https://www.lartusi.com/",
    websiteUrl: "https://www.lartusi.com/",
    sourceUrl: "https://www.lartusi.com/",
    sourceLabel: "Official site",
    booking: { kind: "rolling-days", daysBefore: 14, time: "09:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "lilia",
    name: "Lilia",
    priority: "anchor",
    region: "brooklyn",
    neighborhood: "Williamsburg",
    neighborhoodKey: "williamsburg",
    cuisine: "Italian",
    spend: "$$$",
    spendFor2: "$185-$255",
    summary: "Still one of Williamsburg's big headline tables and still worth the trouble if you want one proper Brooklyn dinner.",
    tip: "Best as the Friday-night anchor if you only do one Williamsburg dinner.",
    address: "567 Union Ave, Brooklyn, NY 11211",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/lilia?venueId=418",
    websiteUrl: "https://www.lilianewyork.com/",
    sourceUrl: "https://blog.resy.com/the-one-who-keeps-the-book/toughest-restaurant-reservations-nyc/",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 28, time: "10:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "don-angie",
    name: "Don Angie",
    priority: "anchor",
    region: "manhattan",
    neighborhood: "West Village",
    neighborhoodKey: "westVillage",
    cuisine: "Italian-American",
    spend: "$$$",
    spendFor2: "$180-$250",
    summary: "Compact room, huge demand, and still one of the cleanest Italian power moves downtown.",
    tip: "Lunch and earlier dinner slots are worth taking if the exact prime-time tables vanish.",
    address: "103 Greenwich Ave, New York, NY 10014",
    bookingUrl: "https://www.opentable.com/r/don-angie-new-york",
    websiteUrl: "https://www.donangie.com/",
    sourceUrl: "https://www.opentable.com/blog/toughest-restaurant-reservations/",
    sourceLabel: "OpenTable",
    booking: { kind: "rolling-days", daysBefore: 7, time: "09:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "via-carota",
    name: "Via Carota",
    priority: "anchor",
    region: "manhattan",
    neighborhood: "West Village",
    neighborhoodKey: "westVillage",
    cuisine: "Italian",
    spend: "$$",
    spendFor2: "$130-$185",
    summary: "A classic downtown power table that still reads as local and worth the line or the drop.",
    tip: "Worth chasing because it pairs perfectly with a shopping-heavy West Village day.",
    address: "51 Grove St, New York, NY 10014",
    bookingUrl: "https://www.viacarota.com/",
    websiteUrl: "https://www.viacarota.com/",
    sourceUrl: "https://www.autores.io/restaurant/viacarota",
    sourceLabel: "AutoRes estimate",
    booking: { kind: "rolling-days", daysBefore: 30, time: "10:00", timeZoneOffset: "-04:00", estimated: true },
  },
  {
    id: "four-horsemen",
    name: "The Four Horsemen",
    priority: "anchor",
    region: "brooklyn",
    neighborhood: "Williamsburg",
    neighborhoodKey: "williamsburg",
    cuisine: "New American",
    spend: "$$$",
    spendFor2: "$170-$240",
    summary: "The best wine-forward Williamsburg reservation on the board if you want a local-coded night.",
    tip: "Ideal for Friday if you want the room quality as much as the food.",
    address: "295 Grand St, Brooklyn, NY 11211",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/the-four-horsemen?venueId=2492",
    sourceUrl: "https://blog.resy.com/the-one-who-keeps-the-book/toughest-restaurant-reservations-nyc/",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 30, time: "07:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "rubirosa",
    name: "Rubirosa",
    priority: "anchor",
    region: "manhattan",
    neighborhood: "Nolita",
    neighborhoodKey: "nolita",
    cuisine: "Italian-American",
    spend: "$$",
    spendFor2: "$110-$165",
    summary: "Best close-to-hotel dinner target if you want something high-energy and easy to sell to anyone.",
    tip: "Great first-night move because it's walking distance from the hotel and still feels like a win.",
    address: "235 Mulberry St, New York, NY 10012",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/rubirosa?venueId=466",
    sourceUrl: "https://blog.resy.com/the-one-who-keeps-the-book/toughest-restaurant-reservations-nyc/",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 7, time: "00:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "laser-wolf",
    name: "Laser Wolf Brooklyn",
    priority: "anchor",
    region: "brooklyn",
    neighborhood: "Williamsburg",
    neighborhoodKey: "williamsburg",
    cuisine: "Israeli",
    spend: "$$",
    spendFor2: "$135-$190",
    summary: "Rooftop skyline fun that still delivers enough food value to feel worth the hype.",
    tip: "Saturday makes the most sense here if you want one louder Brooklyn night.",
    address: "97 Wythe Ave, Brooklyn, NY 11249",
    bookingUrl: "https://www.laserwolfbrooklyn.com/reservations",
    websiteUrl: "https://www.laserwolfbrooklyn.com/reservations",
    sourceUrl: "https://www.laserwolfbrooklyn.com/reservations",
    sourceLabel: "Official site",
    booking: { kind: "rolling-days", daysBefore: 21, time: "10:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "raouls",
    name: "Raoul's",
    priority: "anchor",
    region: "manhattan",
    neighborhood: "SoHo",
    neighborhoodKey: "soho",
    cuisine: "French",
    spend: "$$$",
    spendFor2: "$185-$260",
    summary: "Old-school SoHo glamour and one of the best close-in tables if you want history with the room.",
    tip: "This is the move when you want a downtown dinner that feels unmistakably New York.",
    address: "180 Prince St, New York, NY 10012",
    bookingUrl: "https://raouls.com/",
    websiteUrl: "https://raouls.com/",
    sourceUrl: "https://raouls.com/",
    sourceLabel: "Official site",
    booking: { kind: "rolling-days", daysBefore: 30, time: "08:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "the-nines",
    name: "The Nines",
    priority: "anchor",
    region: "manhattan",
    neighborhood: "NoHo",
    neighborhoodKey: "noho",
    cuisine: "Supper Club",
    spend: "$$$",
    spendFor2: "$190-$280",
    summary: "Piano-room glamour near the hotel with the kind of room that still feels fun when you're dressed up.",
    tip: "Very good for a later dinner followed by nearby drinks in NoHo or the East Village.",
    address: "9 Great Jones St, New York, NY 10012",
    bookingUrl: "https://www.ninesnyc.com/",
    websiteUrl: "https://www.ninesnyc.com/",
    sourceUrl: "https://blog.resy.com/2022/04/how-to-get-into-the-nines/",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 14, time: "00:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "golden-diner",
    name: "Golden Diner",
    priority: "anchor",
    region: "manhattan",
    neighborhood: "Chinatown / LES",
    neighborhoodKey: "chinatown",
    cuisine: "American",
    spend: "$$",
    spendFor2: "$90-$140",
    summary: "Best value-for-dollar restaurant on the page and still one of the easiest all-around recommendations downtown.",
    tip: "If you want one brunch reservation worth planning around, this is it.",
    address: "123 Madison St, New York, NY 10002",
    bookingUrl: "https://www.goldendinerny.com/dine",
    websiteUrl: "https://www.goldendinerny.com/dine",
    sourceUrl: "https://www.goldendinerny.com/dine",
    sourceLabel: "Official site",
    booking: { kind: "rolling-days", daysBefore: 30, time: "00:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "bangkok-supper-club",
    name: "Bangkok Supper Club",
    priority: "anchor",
    region: "manhattan",
    neighborhood: "Meatpacking",
    neighborhoodKey: "meatpacking",
    cuisine: "Thai",
    spend: "$$$",
    spendFor2: "$170-$245",
    summary: "The sharper, more polished Thai dinner if you want a bigger night with cocktails built in.",
    tip: "A good Saturday dinner if you want to stay south of Chelsea Market but still feel dressed.",
    address: "641 Hudson St, New York, NY 10014",
    bookingUrl: "https://www.bangkoksupperclubnyc.com/",
    websiteUrl: "https://www.bangkoksupperclubnyc.com/",
    sourceUrl: "https://blog.resy.com/2023/10/how-to-get-into-bangkok-supper-club-nyc/",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 30, time: "00:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "penny",
    name: "Penny",
    priority: "anchor",
    region: "manhattan",
    neighborhood: "East Village",
    neighborhoodKey: "eastVillage",
    cuisine: "Seafood",
    spend: "$$$",
    spendFor2: "$165-$235",
    summary: "Raw bar energy, seafood nerd appeal, and enough downtown cool to feel like a proper trip-night play.",
    tip: "Works best if you want seafood plus drinks and don't mind a bit of East Village movement afterward.",
    address: "90 E 10th St, New York, NY 10003",
    bookingUrl: "https://www.penny-nyc.com/location/penny/",
    websiteUrl: "https://www.penny-nyc.com/location/penny/",
    sourceUrl: "https://www.penny-nyc.com/location/penny/",
    sourceLabel: "Official site",
    booking: { kind: "rolling-days", daysBefore: 14, time: "09:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "theodora",
    name: "Theodora",
    priority: "anchor",
    region: "brooklyn",
    neighborhood: "Fort Greene",
    neighborhoodKey: "fortGreene",
    cuisine: "Mediterranean",
    spend: "$$$",
    spendFor2: "$190-$270",
    summary: "A stronger deeper-Brooklyn dinner if you want to branch beyond Williamsburg without losing quality.",
    tip: "Best saved for a Brooklyn-heavy day because the neighborhood deserves the detour.",
    address: "7 Greene Ave, Brooklyn, NY 11238",
    bookingUrl: "https://www.theodoranyc.com/",
    websiteUrl: "https://www.theodoranyc.com/",
    sourceUrl: "https://blog.resy.com/the-one-who-keeps-the-book/toughest-restaurant-reservations-nyc/",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 30, time: "09:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "i-cavallini",
    name: "I Cavallini",
    priority: "anchor",
    region: "brooklyn",
    neighborhood: "Williamsburg",
    neighborhoodKey: "williamsburg",
    cuisine: "Italian",
    spend: "$$",
    spendFor2: "$120-$180",
    summary: "Same team credibility as The Four Horsemen, but friendlier on format and spend.",
    tip: "A very good pivot if Lilia and Four Horsemen disappear before you can click.",
    address: "284 Grand St, Brooklyn, NY 11211",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/i-cavallini",
    sourceUrl: "https://blog.resy.com/the-one-who-keeps-the-book/toughest-restaurant-reservations-nyc/",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 14, time: "08:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "thai-diner",
    name: "Thai Diner",
    priority: "anchor",
    region: "manhattan",
    neighborhood: "Nolita",
    neighborhoodKey: "nolita",
    cuisine: "Thai",
    spend: "$$",
    spendFor2: "$95-$145",
    summary: "Close to the hotel, legitimately great, and one of the better value swings if you want something less formal.",
    tip: "Excellent first lunch, brunch, or late dinner move if you want to stay in the SoHo/Nolita lane.",
    address: "186 Mott St, New York, NY 10012",
    bookingUrl: "https://www.thaidiner.com/",
    websiteUrl: "https://www.thaidiner.com/",
    sourceUrl: "https://reservation-booker.com/cities/new-york-ny/venues/thai-diner",
    sourceLabel: "Reservation Booker estimate",
    booking: { kind: "rolling-days", daysBefore: 29, time: "00:00", timeZoneOffset: "-04:00", estimated: true },
  },
  {
    id: "kisa",
    name: "Kisa",
    priority: "anchor",
    region: "manhattan",
    neighborhood: "Lower East Side",
    neighborhoodKey: "lowerEastSide",
    cuisine: "Korean",
    spend: "$$",
    spendFor2: "$110-$165",
    summary: "A tighter, more current LES room that still leaves you with a whole night after dinner.",
    tip: "Great paired with Tigre, Double Chicken Please, or dive bars if you want a Lower East Side night.",
    address: "Kisa, Lower East Side, New York, NY",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/kisa",
    sourceUrl: "https://blog.resy.com/the-one-who-keeps-the-book/toughest-restaurant-reservations-nyc/",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 15, time: "00:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "bistrot-ha",
    name: "Bistrot Ha",
    priority: "anchor",
    region: "manhattan",
    neighborhood: "Lower East Side",
    neighborhoodKey: "lowerEastSide",
    cuisine: "French-Vietnamese",
    spend: "$$$",
    spendFor2: "$160-$225",
    summary: "One of the more current LES reservations on the board if you want something newer than the obvious classics.",
    tip: "This is the kind of dinner that makes the Lower East Side feel fresh again.",
    address: "137 Eldridge St, New York, NY 10002",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/bistrot-ha",
    sourceUrl: "https://blog.resy.com/the-one-who-keeps-the-book/toughest-restaurant-reservations-nyc/",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 6, time: "00:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "sailor",
    name: "Sailor",
    priority: "worth-booking",
    region: "brooklyn",
    neighborhood: "Fort Greene",
    neighborhoodKey: "fortGreene",
    cuisine: "American",
    spend: "$$",
    spendFor2: "$120-$180",
    summary: "A softer Fort Greene bistro night that works when you want Brooklyn without the loudest possible room.",
    tip: "The bar expansion improved your odds if the reservation drop doesn't go your way.",
    address: "228 Dekalb Ave, Brooklyn, NY 11205",
    bookingUrl: "https://www.sailor.nyc/",
    websiteUrl: "https://www.sailor.nyc/",
    sourceUrl: "https://blog.resy.com/2023/10/how-to-get-into-sailor-in-fort-greene/",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 14, time: "11:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "roscioli-nyc",
    name: "Roscioli NYC",
    priority: "worth-booking",
    region: "manhattan",
    neighborhood: "West Village",
    neighborhoodKey: "greenwichVillage",
    cuisine: "Italian",
    spend: "$$$",
    spendFor2: "$180-$260",
    summary: "Roman pasta, good wine, and a room that feels more downtown than formal.",
    tip: "Good if you want a more polished Italian alternative to Don Angie or L'Artusi.",
    address: "43 MacDougal St, New York, NY 10012",
    bookingUrl: "https://www.sevenrooms.com/explore/rosciolinyc/reservations/create/search",
    websiteUrl: "https://www.rosciolinyc.com/",
    sourceUrl: "https://www.sevenrooms.com/explore/rosciolinyc/reservations/create/search",
    sourceLabel: "SevenRooms",
    booking: { kind: "rolling-days", daysBefore: 14, time: "10:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "king",
    name: "King",
    priority: "worth-booking",
    region: "manhattan",
    neighborhood: "SoHo",
    neighborhoodKey: "soho",
    cuisine: "Mediterranean",
    spend: "$$$",
    spendFor2: "$170-$240",
    summary: "A calmer, more elegant SoHo dinner if you want to stay close to the hotel without doing a louder room.",
    tip: "Best for a date-night dinner when you want to look polished and keep the pace a little slower.",
    address: "18 King St, New York, NY 10014",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/king",
    websiteUrl: "https://kingrestaurant.nyc/",
    sourceUrl: "https://kingrestaurant.nyc/",
    sourceLabel: "Official site",
    booking: { kind: "rolling-days", daysBefore: 30, time: "00:00", timeZoneOffset: "-04:00", timeKnown: false, estimated: true },
  },
  {
    id: "torrisi",
    name: "Torrisi",
    priority: "worth-booking",
    region: "manhattan",
    neighborhood: "Nolita",
    neighborhoodKey: "nolita",
    cuisine: "Italian-American",
    spend: "$$$",
    spendFor2: "$220-$320",
    summary: "Big-name, bigger-room Little Italy dining from Major Food without going full tasting-menu mode.",
    tip: "Good if you want a trophy dinner that still feels downtown and high-energy.",
    address: "275 Mulberry St, New York, NY 10012",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/torrisi",
    websiteUrl: "https://www.torrisinyc.com/",
    sourceUrl: "https://www.torrisinyc.com/",
    sourceLabel: "Official site",
    booking: { kind: "rolling-days", daysBefore: 30, time: "00:00", timeZoneOffset: "-04:00", timeKnown: false, estimated: true },
  },
  {
    id: "minetta-tavern",
    name: "Minetta Tavern",
    priority: "worth-booking",
    region: "manhattan",
    neighborhood: "Greenwich Village",
    neighborhoodKey: "greenwichVillage",
    cuisine: "French-American",
    spend: "$$$",
    spendFor2: "$210-$300",
    summary: "Iconic room, serious burger flex, and a classic downtown answer when you want something with history.",
    tip: "This is the old-school Greenwich Village move when you want the room to matter as much as the food.",
    address: "113 MacDougal St, New York, NY 10012",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/minetta-tavern",
    websiteUrl: "https://www.minettatavernny.com/",
    sourceUrl: "https://www.minettatavernny.com/",
    sourceLabel: "Official site",
    booking: { kind: "portal", note: "Reservations run through Resy from the restaurant site, but no release clock is published." },
  },
  {
    id: "estela",
    name: "Estela",
    priority: "worth-booking",
    region: "manhattan",
    neighborhood: "NoHo",
    neighborhoodKey: "noho",
    cuisine: "Mediterranean",
    spend: "$$$",
    spendFor2: "$180-$255",
    summary: "A NoHo staple that still feels current if you want a more food-leaning dinner than a pure scene play.",
    tip: "Very good if you want to eat well and then keep drinking in NoHo or the East Village.",
    address: "47 E Houston St, New York, NY 10012",
    bookingUrl: "https://estelanyc.com/#reservations",
    websiteUrl: "https://estelanyc.com/",
    sourceUrl: "https://estelanyc.com/#reservations",
    sourceLabel: "Official site",
    booking: { kind: "portal", note: "Reservations run through OpenTable from the venue site, but no release clock is published." },
  },
  {
    id: "casino",
    name: "Casino",
    priority: "worth-booking",
    region: "manhattan",
    neighborhood: "Lower East Side",
    neighborhoodKey: "lowerEastSide",
    cuisine: "Italian",
    spend: "$$$",
    spendFor2: "$180-$250",
    summary: "A bigger-room LES option when you want a crowd, cocktails, and pasta without the usual West Village orbit.",
    tip: "This is a great Friday reservation if you want to stay in LES all night afterward.",
    address: "171 E Broadway, New York, NY 10002",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/casino-new-york",
    websiteUrl: "https://www.casinonyc.com/",
    sourceUrl: "https://resy.com/cities/new-york-ny/venues/casino-new-york",
    sourceLabel: "Resy",
    booking: { kind: "portal", note: "The Resy page is live, but it does not publish a release window." },
  },
  {
    id: "corner-bar",
    name: "Corner Bar",
    priority: "worth-booking",
    region: "manhattan",
    neighborhood: "Chinatown",
    neighborhoodKey: "chinatown",
    cuisine: "American",
    spend: "$$$",
    spendFor2: "$190-$270",
    summary: "A dressed, downtown room that works if you want something more polished than the typical Chinatown dinner track.",
    tip: "Best paired with a Chinatown / LES night instead of treated like a standalone destination.",
    address: "8 Delancey St, New York, NY 10002",
    bookingUrl: "https://www.opentable.com/r/corner-bar-reservations-new-york?restref=1470322&lang=en-US&ot_source=Restaurant%20website",
    websiteUrl: "https://cornerbarnyc.com/",
    sourceUrl: "https://cornerbarnyc.com/",
    sourceLabel: "Official site",
    booking: { kind: "portal", note: "Reservations are available through OpenTable from the venue site, but no release clock is published." },
  },
  {
    id: "cervos",
    name: "Cervo's",
    priority: "worth-booking",
    region: "manhattan",
    neighborhood: "Lower East Side",
    neighborhoodKey: "lowerEastSide",
    cuisine: "Spanish",
    spend: "$$",
    spendFor2: "$120-$175",
    summary: "A local-favorite seafood and sherry dinner if you want the meal to feel more downtown than hype-driven.",
    tip: "Good if you want something cooler and more casual than the standard trophy reservation list.",
    address: "43 Canal St, New York, NY 10002",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/cervos",
    websiteUrl: "https://www.cervosnyc.com/",
    sourceUrl: "https://resy.com/cities/new-york-ny/venues/cervos",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 14, time: "12:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "dame",
    name: "Dame",
    priority: "worth-booking",
    region: "manhattan",
    neighborhood: "Greenwich Village",
    neighborhoodKey: "greenwichVillage",
    cuisine: "Seafood",
    spend: "$$$",
    spendFor2: "$175-$245",
    summary: "The fish-and-chips crowd magnet that still works because the room and the cooking both hold up.",
    tip: "A sharp choice if you want seafood but Penny feels too counter-shaped for the night.",
    address: "87 MacDougal St, New York, NY 10012",
    bookingUrl: "https://www.damenewyork.com/reserve",
    websiteUrl: "https://www.damenewyork.com/",
    sourceUrl: "https://www.damenewyork.com/reserve",
    sourceLabel: "Official reserve page",
    booking: { kind: "rolling-days", daysBefore: 21, time: "12:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "nudibranch",
    name: "Nudibranch",
    priority: "worth-booking",
    region: "manhattan",
    neighborhood: "East Village",
    neighborhoodKey: "eastVillage",
    cuisine: "Asian Fusion",
    spend: "$$",
    spendFor2: "$120-$170",
    summary: "A strong East Village choice if you want something more chefy and current without losing the downtown looseness.",
    tip: "Useful when you want a dinner that still leaves room in the budget for better cocktails after.",
    address: "125 1st Ave, New York, NY 10003",
    bookingUrl: "https://nudibranchnyc.com/make-a-reservation",
    websiteUrl: "https://nudibranchnyc.com/",
    sourceUrl: "https://nudibranchnyc.com/make-a-reservation",
    sourceLabel: "Official reserve page",
    booking: { kind: "portal", note: "Reservations run through OpenTable from the restaurant site, but no release clock is published." },
  },
  {
    id: "llama-san",
    name: "Llama San",
    priority: "worth-booking",
    region: "manhattan",
    neighborhood: "West Village",
    neighborhoodKey: "greenwichVillage",
    cuisine: "Peruvian-Japanese",
    spend: "$$$",
    spendFor2: "$180-$255",
    summary: "A smarter downtown move if you want something globally inflected instead of another Italian night.",
    tip: "Best used to break up the pasta-heavy options when you still want a serious dinner.",
    address: "359 6th Ave, New York, NY 10014",
    bookingUrl: searchUrl("Llama San NYC reservations"),
    websiteUrl: searchUrl("Llama San NYC official site"),
    booking: { kind: "portal", note: "Reservations are portal-based; no public countdown posted." },
  },
  {
    id: "claud",
    name: "Claud",
    priority: "worth-booking",
    region: "manhattan",
    neighborhood: "East Village",
    neighborhoodKey: "eastVillage",
    cuisine: "French-American",
    spend: "$$$",
    spendFor2: "$165-$235",
    summary: "One of the cleaner East Village dinner rooms if you want a sharp wine list and a more adult energy.",
    tip: "Good if you want dinner to lead naturally into a cocktail-heavy East Village night.",
    address: "90 E 10th St, New York, NY 10003",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/claud",
    websiteUrl: "https://www.claudnyc.com/",
    sourceUrl: "https://resy.com/cities/new-york-ny/venues/claud",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 14, time: "09:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "misi",
    name: "Misi",
    priority: "worth-booking",
    region: "brooklyn",
    neighborhood: "Williamsburg",
    neighborhoodKey: "williamsburg",
    cuisine: "Italian",
    spend: "$$$",
    spendFor2: "$170-$240",
    summary: "The cleaner, calmer sister play to Lilia if you still want Missy Robbins pasta but a different room.",
    tip: "Perfect if Lilia is gone but you still want a strong Williamsburg Italian dinner.",
    address: "329 Kent Ave, Brooklyn, NY 11249",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/misi",
    websiteUrl: "https://www.misinewyork.com/",
    sourceUrl: "https://www.misinewyork.com/",
    sourceLabel: "Official site",
    booking: { kind: "portal", note: "Reservations route to Resy from the restaurant site, but no release clock is published." },
  },
  {
    id: "le-crocodile",
    name: "Le Crocodile",
    priority: "worth-booking",
    region: "brooklyn",
    neighborhood: "Williamsburg",
    neighborhoodKey: "williamsburg",
    cuisine: "French",
    spend: "$$$",
    spendFor2: "$185-$260",
    summary: "A safer Williamsburg hotel-adjacent French room if you want something polished and lower variance.",
    tip: "Good if you want Brooklyn but don't need the hardest possible table every single night.",
    address: "80 Wythe Ave, Brooklyn, NY 11249",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/le-crocodile",
    websiteUrl: "https://www.lecrocodile.com/",
    sourceUrl: "https://resy.com/cities/new-york-ny/venues/le-crocodile",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 28, time: "00:00", timeZoneOffset: "-04:00", timeKnown: false, estimated: true },
  },
  {
    id: "wenwen",
    name: "WenWen",
    priority: "worth-booking",
    region: "brooklyn",
    neighborhood: "Greenpoint",
    neighborhoodKey: "greenpoint",
    cuisine: "Taiwanese",
    spend: "$$",
    spendFor2: "$115-$165",
    summary: "A strong Greenpoint/Williamsburg-area meal if you want something playful and not too predictable.",
    tip: "Best paired with Eavesdrop or a Greenpoint bar circuit instead of treated as a standalone trek.",
    address: "1025 Manhattan Ave, Brooklyn, NY 11222",
    bookingUrl: "https://www.wenwenbrooklyn.com/",
    websiteUrl: "https://www.wenwenbrooklyn.com/",
    booking: { kind: "portal", note: "Venue portal is live; booking release timing is not published." },
  },
  {
    id: "shmone",
    name: "Shmoné",
    priority: "worth-booking",
    region: "manhattan",
    neighborhood: "West Village",
    neighborhoodKey: "westVillage",
    cuisine: "Israeli",
    spend: "$$$",
    spendFor2: "$190-$270",
    summary: "A more polished Israeli dinner if you want something sharper and more intimate than Laser Wolf.",
    tip: "Useful when you want serious food but still a downtown room instead of a tasting-menu temple.",
    address: "61 W 8th St, New York, NY 10011",
    bookingUrl: "https://www.shmonenyc.com/",
    websiteUrl: "https://www.shmonenyc.com/",
    booking: { kind: "portal", note: "The booking portal is live with no public drop clock." },
  },
  {
    id: "63-clinton",
    name: "63 Clinton",
    priority: "worth-booking",
    region: "manhattan",
    neighborhood: "Lower East Side",
    neighborhoodKey: "lowerEastSide",
    cuisine: "American",
    spend: "$$$",
    spendFor2: "$230-$310",
    summary: "One of the more food-leaning LES choices if you want a serious meal that still stays downtown.",
    tip: "A stronger pick when dinner is the event and drinks come second.",
    address: "63 Clinton St, New York, NY 10002",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/sixty-three-clinton",
    websiteUrl: "https://www.63clinton.com/",
    sourceUrl: "https://resy.com/cities/new-york-ny/venues/sixty-three-clinton",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 21, time: "00:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "potluck-club",
    name: "Potluck Club",
    priority: "worth-booking",
    region: "manhattan",
    neighborhood: "Chinatown",
    neighborhoodKey: "chinatown",
    cuisine: "Cantonese-American",
    spend: "$$",
    spendFor2: "$110-$165",
    summary: "Fun, downtown, and easier on the wallet if you want a looser Chinatown dinner with real personality.",
    tip: "Good if you want a more playful group-energy dinner and less of a scene-first room.",
    address: "133 Chrystie St, New York, NY 10002",
    bookingUrl: "https://www.opentable.com/r/potluck-club-new-york",
    websiteUrl: "https://www.potluckclubny.com/",
    sourceUrl: "https://www.potluckclubny.com/",
    sourceLabel: "Official site",
    booking: { kind: "portal", note: "Reservations are available through OpenTable from the venue site, but no release clock is published." },
  },
  {
    id: "antons",
    name: "Anton's",
    priority: "worth-booking",
    region: "manhattan",
    neighborhood: "West Village",
    neighborhoodKey: "westVillage",
    cuisine: "French-American",
    spend: "$$$",
    spendFor2: "$170-$245",
    summary: "A big-room downtown answer if you want something classic and a little less brutal than the top-tier tables.",
    tip: "Good for the night you want a real New York room without sweating the reservation quite as hard.",
    address: "570 Hudson St, New York, NY 10014",
    bookingUrl: "https://www.antonsnyc.com/",
    websiteUrl: "https://www.antonsnyc.com/",
    booking: { kind: "portal", note: "Reservations are available through the restaurant portal." },
  },
];

const bars = [
  {
    id: "double-chicken-please",
    name: "Double Chicken Please",
    priority: "book",
    style: "cocktail",
    region: "manhattan",
    neighborhood: "Lower East Side",
    neighborhoodKey: "lowerEastSide",
    spend: "$$",
    summary: "Still the highest-upside hard-ticket cocktail stop downtown.",
    tip: "The back room is the reservation play; the front room is still a valid walk-in backup.",
    address: "115 Allen St, New York, NY 10002",
    bookingUrl: "https://doublechickenplease.com/pages/visitus",
    websiteUrl: "https://doublechickenplease.com/pages/visitus",
    sourceUrl: "https://doublechickenplease.com/pages/visitus",
    sourceLabel: "Official site",
    booking: { kind: "rolling-days", daysBefore: 6, time: "00:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "tigre",
    name: "Tigre",
    priority: "book",
    style: "cocktail",
    region: "manhattan",
    neighborhood: "Lower East Side",
    neighborhoodKey: "lowerEastSide",
    spend: "$$",
    summary: "Sleek martinis and a better-managed scene than some of the louder downtown bar rooms.",
    tip: "The bar is walk-in only, so late-night remains a real backup plan.",
    address: "105 Rivington St, New York, NY 10002",
    bookingUrl: "https://tigrenyc.com/",
    websiteUrl: "https://tigrenyc.com/",
    sourceUrl: "https://blog.resy.com/2024/03/how-to-get-into-tigre/",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 30, time: "00:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "bar-blondeau",
    name: "Bar Blondeau",
    priority: "book",
    style: "rooftop",
    region: "brooklyn",
    neighborhood: "Williamsburg",
    neighborhoodKey: "williamsburg",
    spend: "$$",
    summary: "The cleaner rooftop finish if you want skyline without full tourist-deck energy.",
    tip: "Works best before or after a Williamsburg dinner instead of as your only destination.",
    address: "80 Wythe Ave 6th Floor, Brooklyn, NY 11249",
    bookingUrl: "https://www.barblondeau.com/",
    websiteUrl: "https://www.barblondeau.com/",
    sourceUrl: "https://www.barblondeau.com/",
    sourceLabel: "Official site",
    booking: { kind: "rolling-days", daysBefore: 28, time: "00:00", timeZoneOffset: "-04:00", estimated: true },
  },
  {
    id: "red-room-bar",
    name: "Red Room Bar",
    priority: "book",
    style: "cocktail",
    region: "manhattan",
    neighborhood: "Financial District",
    neighborhoodKey: "financialDistrict",
    spend: "$$",
    summary: "Most fashion-adjacent drink on the board and a strong Lower Manhattan polish play.",
    tip: "Best as a polished final drink rather than your only bar of the night.",
    address: "One Wall St, New York, NY 10005",
    bookingUrl: "https://www.theredroombar.com/",
    websiteUrl: "https://www.theredroombar.com/",
    sourceUrl: "https://blog.resy.com/2025/03/maison-passerelle-nyc/",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 28, time: "10:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "maison-premiere",
    name: "Maison Premiere",
    priority: "book",
    style: "cocktail",
    region: "brooklyn",
    neighborhood: "Williamsburg",
    neighborhoodKey: "williamsburg",
    spend: "$$$",
    summary: "Classic absinthe-and-oysters Williamsburg glamour in a room that still feels worth dressing up for.",
    tip: "Ideal when you want a more romantic bar night than the louder Williamsburg rooftops.",
    address: "298 Bedford Ave, Brooklyn, NY 11249",
    bookingUrl: "https://maisonpremiere.com/menus/",
    websiteUrl: "https://maisonpremiere.com/menus/",
    sourceUrl: "https://maisonpremiere.com/menus/",
    sourceLabel: "Official site",
    booking: { kind: "calendar-month", monthsBefore: 1, time: "00:00", timeZoneOffset: "-04:00", estimated: true },
  },
  {
    id: "eavesdrop",
    name: "Eavesdrop",
    priority: "book",
    style: "listening",
    region: "brooklyn",
    neighborhood: "Greenpoint",
    neighborhoodKey: "greenpoint",
    spend: "$$",
    summary: "A real listening bar with enough atmosphere to justify the Greenpoint detour.",
    tip: "Best after a Williamsburg dinner; after midnight it shifts to walk-in only.",
    address: "674 Manhattan Ave, Brooklyn, NY 11222",
    bookingUrl: "https://www.eavesdrop.nyc/",
    websiteUrl: "https://www.eavesdrop.nyc/",
    sourceUrl: "https://blog.resy.com/2022/07/how-to-get-into-eavesdrop-new-york/",
    sourceLabel: "Resy",
    booking: { kind: "rolling-days", daysBefore: 14, time: "12:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "overstory",
    name: "Overstory",
    priority: "book",
    style: "rooftop",
    region: "manhattan",
    neighborhood: "Financial District",
    neighborhoodKey: "financialDistrict",
    spend: "$$$",
    summary: "Big-view FiDi flex if you want one panoramic cocktail moment downtown.",
    tip: "This is better as a pre-booked statement drink than a spontaneous wander-in.",
    address: "70 Pine St, New York, NY 10005",
    bookingUrl: "https://www.overstory-nyc.com/",
    websiteUrl: "https://www.overstory-nyc.com/",
    sourceUrl: "https://www.autores.io/restaurant/overstory",
    sourceLabel: "AutoRes estimate",
    booking: { kind: "rolling-days", daysBefore: 14, time: "10:00", timeZoneOffset: "-04:00", estimated: true },
  },
  {
    id: "employees-only",
    name: "Employees Only",
    priority: "book",
    style: "cocktail",
    region: "manhattan",
    neighborhood: "West Village",
    neighborhoodKey: "westVillage",
    spend: "$$",
    summary: "An old reliable if you want a classic West Village cocktail room and not just TikTok-buzz bars.",
    tip: "Good late when you want the bar to carry the rest of the night.",
    address: "510 Hudson St, New York, NY 10014",
    bookingUrl: "https://www.employeesonlynyc.com/",
    websiteUrl: "https://www.employeesonlynyc.com/",
    booking: { kind: "portal", note: "Reservations and walk-ins both exist; use the live venue page." },
  },
  {
    id: "dante",
    name: "Dante",
    priority: "book",
    style: "cocktail",
    region: "manhattan",
    neighborhood: "West Village",
    neighborhoodKey: "westVillage",
    spend: "$$",
    summary: "The West Village aperitivo play if you want a more polished start to the night.",
    tip: "Useful before dinner if you want the scene but not a whole late-night production.",
    address: "551 Hudson St, New York, NY 10014",
    bookingUrl: "https://www.dante-nyc.com/",
    websiteUrl: "https://www.dante-nyc.com/",
    booking: { kind: "portal", note: "Use the venue portal for current reservations." },
  },
  {
    id: "sip-and-guzzle",
    name: "Sip & Guzzle",
    priority: "book",
    style: "cocktail",
    region: "manhattan",
    neighborhood: "Greenwich Village",
    neighborhoodKey: "greenwichVillage",
    spend: "$$",
    summary: "A newer cocktail hit if you want something more current than the old downtown standards.",
    tip: "Best when you want serious drinks but not the line chaos of the usual big-name spots.",
    address: "29 Cornelia St, New York, NY 10014",
    bookingUrl: "https://www.sipandguzzlenyc.com/",
    websiteUrl: "https://www.sipandguzzlenyc.com/",
    booking: { kind: "portal", note: "Reservations are live through the venue site." },
  },
  {
    id: "sunken-harbor-club",
    name: "Sunken Harbor Club",
    priority: "book",
    style: "cocktail",
    region: "brooklyn",
    neighborhood: "Cobble Hill",
    neighborhoodKey: "cobbleHill",
    spend: "$$",
    summary: "A destination tiki room if you want the bar to be the event and don't mind heading deeper into Brooklyn.",
    tip: "This is the one to choose when you want a real theme room done properly, not ironically.",
    address: "372 Fulton St, Brooklyn, NY 11201",
    bookingUrl: "https://www.sunkenharbor.club/",
    websiteUrl: "https://www.sunkenharbor.club/",
    booking: { kind: "portal", note: "Check the venue page for current booking and walk-in rules." },
  },
  {
    id: "long-island-bar",
    name: "Long Island Bar",
    priority: "local",
    style: "cocktail",
    region: "brooklyn",
    neighborhood: "Cobble Hill",
    neighborhoodKey: "cobbleHill",
    spend: "$$",
    summary: "A proper neighborhood cocktail bar when you want Brooklyn energy without a hype-tax room.",
    tip: "Good if you want a better local-feeling drink than a rooftop or big-name reservation bar.",
    address: "110 Atlantic Ave, Brooklyn, NY 11201",
    websiteUrl: mapsSearchUrl("Long Island Bar Brooklyn"),
    booking: { kind: "walk-in", note: "Treat this as a walk-in bar." },
  },
  {
    id: "attaboy",
    name: "Attaboy",
    priority: "local",
    style: "cocktail",
    region: "manhattan",
    neighborhood: "Lower East Side",
    neighborhoodKey: "lowerEastSide",
    spend: "$$",
    summary: "Still one of the most respected LES cocktails if you are willing to line up and let the room happen to you.",
    tip: "This is a walk-in-only commitment play, not a tidy scheduled drink.",
    address: "134 Eldridge St, New York, NY 10002",
    websiteUrl: "https://attaboy.us/",
    booking: { kind: "walk-in", note: "Walk-in only." },
  },
  {
    id: "169-bar",
    name: "169 Bar",
    priority: "dive",
    style: "dive",
    region: "manhattan",
    neighborhood: "Lower East Side",
    neighborhoodKey: "lowerEastSide",
    spend: "$",
    summary: "The iconic LES dive answer if you want the bar to feel messy in the right way.",
    tip: "Perfect after dinner when you no longer care about curated vibes.",
    address: "169 E Broadway, New York, NY 10002",
    websiteUrl: mapsSearchUrl("169 Bar New York"),
    booking: { kind: "walk-in", note: "Walk-in only." },
  },
  {
    id: "clockwork-bar",
    name: "Clockwork Bar",
    priority: "dive",
    style: "dive",
    region: "manhattan",
    neighborhood: "Lower East Side",
    neighborhoodKey: "lowerEastSide",
    spend: "$",
    summary: "A true LES dive if you want cheap drinks, loud music, and absolutely no pretense.",
    tip: "This is your backup when all polished cocktail plans start to feel too choreographed.",
    address: "54 Essex St, New York, NY 10002",
    websiteUrl: "https://clockworknyc.com/",
    booking: { kind: "walk-in", note: "Walk-in only." },
  },
  {
    id: "rocka-rolla",
    name: "Rocka Rolla",
    priority: "dive",
    style: "dive",
    region: "brooklyn",
    neighborhood: "Williamsburg",
    neighborhoodKey: "williamsburg",
    spend: "$",
    summary: "A Williamsburg dive that still feels local enough to justify the stop after the fancier dinner rooms.",
    tip: "Best after midnight when rooftop energy starts feeling tired.",
    address: "486 Metropolitan Ave, Brooklyn, NY 11211",
    websiteUrl: mapsSearchUrl("Rocka Rolla Brooklyn"),
    booking: { kind: "walk-in", note: "Walk-in only." },
  },
  {
    id: "milanos-bar",
    name: "Milano's Bar",
    priority: "dive",
    style: "dive",
    region: "manhattan",
    neighborhood: "SoHo",
    neighborhoodKey: "soho",
    spend: "$",
    summary: "A true old-school downtown bar if you want grit and history over trendiness.",
    tip: "Excellent as a nearby late drink when you want to stay close to the hotel.",
    address: "51 E Houston St, New York, NY 10012",
    websiteUrl: "https://milanosbar.com/",
    booking: { kind: "walk-in", note: "Walk-in only." },
  },
  {
    id: "lucky-dog",
    name: "Lucky Dog",
    priority: "dive",
    style: "dive",
    region: "brooklyn",
    neighborhood: "Williamsburg",
    neighborhoodKey: "williamsburg",
    spend: "$",
    summary: "A reliable Williamsburg dive if you want a lower-stakes bar after a bigger dinner reservation.",
    tip: "Works especially well when you want to end the night cheaply and keep moving.",
    address: "303 Bedford Ave, Brooklyn, NY 11211",
    websiteUrl: mapsSearchUrl("Lucky Dog Williamsburg"),
    booking: { kind: "walk-in", note: "Walk-in only." },
  },
];

const cocktailBars = [
  {
    id: "cocktail-superbueno",
    name: "Superbueno",
    priority: "book",
    style: "cocktail",
    region: "manhattan",
    neighborhood: "East Village",
    neighborhoodKey: "eastVillage",
    spend: "$$",
    summary: "One of the sharpest current downtown cocktail rooms and still the easiest way to book a big East Village drinks night that feels plugged in.",
    tip: "Best when you want one modern-hit cocktail stop instead of bouncing around three weaker bars.",
    address: "13 1st Ave, New York, NY 10003",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/superbueno",
    websiteUrl: "https://www.superbuenonyc.com/",
    sourceUrl: "https://www.superbuenonyc.com/",
    sourceLabel: "Official site",
    booking: { kind: "portal", note: "Reservations run through Resy from the official site, but no reliable release clock is published." },
  },
  {
    id: "cocktail-pdt",
    name: "PDT",
    priority: "book",
    style: "cocktail",
    region: "manhattan",
    neighborhood: "East Village",
    neighborhoodKey: "eastVillage",
    spend: "$$",
    summary: "Still one of the classic New York cocktail reservations that feels worth doing at least once if you care about the city’s bar canon.",
    tip: "This works better as a deliberate first or last stop than as a casual drop-in between dinner plans.",
    address: "113 St Marks Pl, New York, NY 10009",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/pdt",
    websiteUrl: "https://pdtnyc.com/",
    sourceUrl: "https://pdtnyc.com/",
    sourceLabel: "Official site",
    booking: { kind: "portal", note: "Book through Resy from the official site; the venue does not publish a clean drop time." },
  },
  {
    id: "cocktail-mace",
    name: "Mace",
    priority: "book",
    style: "cocktail",
    region: "manhattan",
    neighborhood: "Greenwich Village",
    neighborhoodKey: "greenwichVillage",
    spend: "$$",
    summary: "A serious-spirit Greenwich Village room when you want cocktails to be the point of the night and not just the pregame.",
    tip: "A better fit for a focused drinks reservation than a loud scene bar.",
    address: "35 W 8th St, New York, NY 10011",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/mace",
    websiteUrl: "https://www.macerestaurant.com/",
    sourceUrl: "https://www.macerestaurant.com/",
    sourceLabel: "Official site",
    booking: { kind: "portal", note: "Reservations route through Resy from the official site, but no current release clock is published." },
  },
  {
    id: "cocktail-death-and-co",
    name: "Death & Co",
    priority: "book",
    style: "cocktail",
    region: "manhattan",
    neighborhood: "East Village",
    neighborhoodKey: "eastVillage",
    spend: "$$",
    summary: "Still one of the benchmark East Village cocktail rooms if you want the institutional classic, not just the latest hype opening.",
    tip: "Choose this when you want polished service and depth over flash.",
    address: "433 E 6th St, New York, NY 10009",
    bookingUrl: "https://www.exploretock.com/deathconyc",
    websiteUrl: "https://www.deathandcompany.com/location/new-york-city/",
    sourceUrl: "https://www.deathandcompany.com/location/new-york-city/",
    sourceLabel: "Official site",
    booking: { kind: "portal", note: "Bookings run through Tock from the official site; no reliable advance-drop time is published." },
  },
  {
    id: "cocktail-dead-rabbit",
    name: "The Dead Rabbit",
    priority: "book",
    style: "cocktail",
    region: "manhattan",
    neighborhood: "Financial District",
    neighborhoodKey: "financialDistrict",
    spend: "$$",
    summary: "The downtown Irish-meets-cocktail institution when you want one FiDi bar that still feels definitively New York.",
    tip: "The move is a deliberate reservation, not a random post-dinner wander.",
    address: "30 Water St, New York, NY 10004",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/the-dead-rabbit",
    websiteUrl: "https://www.deadrabbitnyc.com/",
    sourceUrl: "https://www.deadrabbitnyc.com/",
    sourceLabel: "Official site",
    booking: { kind: "portal", note: "Reservations route through the official site and Resy, but the venue does not publish a drop schedule." },
  },
  {
    id: "cocktail-double-chicken-please",
    name: "Double Chicken Please",
    priority: "book",
    style: "cocktail",
    region: "manhattan",
    neighborhood: "Lower East Side",
    neighborhoodKey: "lowerEastSide",
    spend: "$$",
    summary: "Still the hardest cocktail ticket downtown if you want the back-room experience and not just the front-bar spillover.",
    tip: "Only worth chasing if cocktails are the mission, because the booking pressure is real.",
    address: "115 Allen St, New York, NY 10002",
    bookingUrl: "https://doublechickenplease.com/pages/visitus",
    websiteUrl: "https://doublechickenplease.com/pages/visitus",
    sourceUrl: "https://doublechickenplease.com/pages/visitus",
    sourceLabel: "Official site",
    booking: { kind: "rolling-days", daysBefore: 6, time: "00:00", timeZoneOffset: "-04:00", estimated: false },
  },
  {
    id: "cocktail-overstory",
    name: "Overstory",
    priority: "book",
    style: "rooftop",
    region: "manhattan",
    neighborhood: "Financial District",
    neighborhoodKey: "financialDistrict",
    spend: "$$$",
    summary: "The panoramic cocktail flex if you want one skyline statement stop in Lower Manhattan.",
    tip: "Best reserved as the polished finish to a downtown dinner, not as a backup plan.",
    address: "70 Pine St, New York, NY 10005",
    bookingUrl: "https://www.overstory-nyc.com/",
    websiteUrl: "https://www.overstory-nyc.com/",
    sourceUrl: "https://www.autores.io/restaurant/overstory",
    sourceLabel: "AutoRes estimate",
    booking: { kind: "rolling-days", daysBefore: 14, time: "10:00", timeZoneOffset: "-04:00", estimated: true },
  },
  {
    id: "cocktail-angels-share",
    name: "Angel's Share",
    priority: "local",
    style: "cocktail",
    region: "manhattan",
    neighborhood: "West Village",
    neighborhoodKey: "westVillage",
    spend: "$$$",
    summary: "A quieter, more romantic cocktail room when you want the night to feel refined instead of scene-driven.",
    tip: "Good for a lower-volume date-night drink after a West Village dinner.",
    address: "45 Grove St, New York, NY 10014",
    bookingUrl: "https://www.angelssharenyc.com/",
    websiteUrl: "https://www.angelssharenyc.com/",
    sourceUrl: "https://www.angelssharenyc.com/",
    sourceLabel: "Official site",
    booking: { kind: "walk-in", note: "The official site currently lists this as walk-in only." },
  },
  {
    id: "cocktail-paradise-lost",
    name: "Paradise Lost",
    priority: "local",
    style: "cocktail",
    region: "manhattan",
    neighborhood: "East Village",
    neighborhoodKey: "eastVillage",
    spend: "$$",
    summary: "A more playful tropical-cocktail answer when you want downtown energy without another polished black-walled room.",
    tip: "This is the better move when you want personality and fun over white-tablecloth cocktail seriousness.",
    address: "100 2nd Ave, New York, NY 10003",
    bookingUrl: "https://www.paradiselost.nyc/",
    websiteUrl: "https://www.paradiselost.nyc/",
    sourceUrl: "https://www.paradiselost.nyc/",
    sourceLabel: "Official site",
    booking: { kind: "walk-in", note: "The official site currently lists this as walk-in only." },
  },
  {
    id: "cocktail-maison-premiere",
    name: "Maison Premiere",
    priority: "book",
    style: "cocktail",
    region: "brooklyn",
    neighborhood: "Williamsburg",
    neighborhoodKey: "williamsburg",
    spend: "$$$",
    summary: "The strongest Williamsburg cocktail reservation if you want old-school glamour rather than a louder rooftop scene.",
    tip: "This is the booking to pair with a proper Williamsburg dinner when you want the bar to feel like its own event.",
    address: "298 Bedford Ave, Brooklyn, NY 11249",
    bookingUrl: "https://maisonpremiere.com/menus/",
    websiteUrl: "https://maisonpremiere.com/menus/",
    sourceUrl: "https://maisonpremiere.com/menus/",
    sourceLabel: "Official site",
    booking: { kind: "calendar-month", monthsBefore: 1, time: "00:00", timeZoneOffset: "-04:00", estimated: true },
  },
  {
    id: "cocktail-clover-club",
    name: "Clover Club",
    priority: "book",
    style: "cocktail",
    region: "brooklyn",
    neighborhood: "Cobble Hill",
    neighborhoodKey: "cobbleHill",
    spend: "$$",
    summary: "Still one of Brooklyn's most reliable classic-cocktail rooms if you want quality without gimmickry.",
    tip: "This is the Brooklyn answer when you want cocktails to feel established and easy rather than trendy.",
    address: "210 Smith St, Brooklyn, NY 11201",
    bookingUrl: "https://resy.com/cities/new-york-ny/venues/clover-club",
    websiteUrl: "https://www.cloverclubny.com/",
    sourceUrl: "https://www.cloverclubny.com/",
    sourceLabel: "Official site",
    booking: { kind: "portal", note: "Reservations run through Resy from the official site, but no reliable release clock is published." },
  },
  {
    id: "cocktail-sunken-harbor-club",
    name: "Sunken Harbor Club",
    priority: "book",
    style: "cocktail",
    region: "brooklyn",
    neighborhood: "Cobble Hill",
    neighborhoodKey: "cobbleHill",
    spend: "$$",
    summary: "A destination tiki room when you want the bar itself to be the event and not just a place for one round.",
    tip: "Go here when you want Brooklyn drinks with actual theatrical payoff.",
    address: "372 Fulton St, Brooklyn, NY 11201",
    bookingUrl: "https://www.sunkenharbor.club/",
    websiteUrl: "https://www.sunkenharbor.club/",
    sourceUrl: "https://www.sunkenharbor.club/",
    sourceLabel: "Official site",
    booking: { kind: "portal", note: "Use the official site for the latest booking or walk-in rules; no clean drop schedule is published." },
  },
];

const guinnessSpots = [
  {
    rank: 1,
    name: "Swift Hibernian Lounge",
    neighborhood: "East Village",
    neighborhoodKey: "eastVillage",
    borough: "Manhattan",
    location: "34 E 4th St",
    note: "Best all-around Guinness answer if you want a real Irish bar south of Union Square.",
  },
  {
    rank: 2,
    name: "The Dead Rabbit",
    neighborhood: "Financial District",
    neighborhoodKey: "financialDistrict",
    borough: "Manhattan",
    location: "30 Water St",
    note: "The most famous downtown Irish pour, even if the room is far more polished than a dive.",
  },
  {
    rank: 3,
    name: "11th Street Bar",
    neighborhood: "East Village",
    neighborhoodKey: "eastVillage",
    borough: "Manhattan",
    location: "510 E 11th St",
    note: "A dependable pint in a true neighborhood Irish bar.",
  },
  {
    rank: 4,
    name: "Hartley's",
    neighborhood: "Clinton Hill",
    neighborhoodKey: "clintonHill",
    borough: "Brooklyn",
    location: "232 DeKalb Ave",
    note: "The Brooklyn answer if you care about the pour and not just the Guinness logo.",
  },
  {
    rank: 5,
    name: "Iona",
    neighborhood: "Williamsburg",
    neighborhoodKey: "williamsburg",
    borough: "Brooklyn",
    location: "180 Grand St",
    note: "Classic Williamsburg Irish pub and still one of the easiest solid pints in your target zone.",
  },
  {
    rank: 6,
    name: "The Craic",
    neighborhood: "Williamsburg",
    neighborhoodKey: "williamsburg",
    borough: "Brooklyn",
    location: "488 Driggs Ave",
    note: "If you want Williamsburg and Guinness specifically, this belongs on the page.",
  },
  {
    rank: 7,
    name: "Montero's Bar & Grill",
    neighborhood: "Brooklyn Heights",
    neighborhoodKey: "brooklynHeights",
    borough: "Brooklyn",
    location: "73 Atlantic Ave",
    note: "An old-school Brooklyn bar where the pint tastes better because the room has zero interest in trends.",
  },
  {
    rank: 8,
    name: "Paddy's of Park Slope",
    neighborhood: "Park Slope",
    neighborhoodKey: "parkSlope",
    borough: "Brooklyn",
    location: "273 13th St",
    note: "Further south, but one of the stronger Brooklyn pints if you end up deeper in the borough.",
  },
  {
    rank: 9,
    name: "O'Hanlon's",
    neighborhood: "East Village",
    neighborhoodKey: "eastVillage",
    borough: "Manhattan",
    location: "349 E 14th St",
    note: "A rougher East Village option if you want the Guinness and the dive energy together.",
  },
  {
    rank: 10,
    name: "The Full Shilling",
    neighborhood: "Williamsburg",
    neighborhoodKey: "williamsburg",
    borough: "Brooklyn",
    location: "160 Ainslie St",
    note: "Another solid Williamsburg pint when you want Irish-bar comfort without crossing back to Manhattan.",
  },
];

window.tripPlannerData = {
  hotel,
  tripDates,
  neighborhoodCenters,
  restaurants,
  bars,
  cocktailBars,
  guinnessSpots,
  searchUrl,
  mapsSearchUrl,
};
